### ISSUE TITLE
NameError: name 'ERROR_EXECUTING_CODEQL' is not defined

### ISSUE THREAD

**Issue by ssst0n3** [microsoft/codeql-container#32]
```
# docker run --rm --name codeql-container -e CODEQL_CLI_ARGS="resolve qlpacks"  mcr.microsoft.com/cstsectools/codeql-container

Could not determine existing codeql version
Traceback (most recent call last):
  File "/usr/local/startup_scripts/setup.py", line 57, in <module>
    setup()
  File "/usr/local/startup_scripts/setup.py", line 39, in setup
    get_latest_codeql(args)
  File "/usr/local/startup_scripts/setup.py", line 44, in get_latest_codeql
    current_installed_version = codeql.get_current_local_version()
  File "/usr/local/startup_scripts/libs/codeql.py", line 74, in get_current_local_version
    exit(ERROR_EXECUTING_CODEQL)
NameError: name 'ERROR_EXECUTING_CODEQL' is not defined
Error 1 executing from command.
Exiting...
Command Output: 
[2021-08-16 02:50:18,394] INFO: Starting setup...
```

**Comment by jacobmsft** [comment]
Missed closing this issue, this is resolved now. please reopen if it persists
